name: Teste Telegram

on: workflow_dispatch

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensagem para Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'ðŸ”¥ Teste do bot funcionando testando!'
